version: '3'
services:
  pci:
    image: flexibleir/compliance:0.5
    command: /main
    ports:
      - "80:8080"
    networks:
      - localnet  
  pen:
    image: akshayvenkatesha/pen:0.3
    command: python /code/orchestrator.py
    stdin_open: true
    tty: true
    privileged: true
    ports:
      - "5000:5000"
    networks:
      - localnet
    volumes:
      - data:/data      
networks:
  localnet:
volumes:
  data:
  
