version: '3'
services:
  pci:
    image: flexibleir/compliance:0.5
    command: /main
    ports:
      - "80:8080"
    networks:
      - localnet  
  pen:
    image: akshayvenkatesha/pen:0.1
    command: /bin/bash
    stdin_open: true
    tty: true
    privileged: true
    networks:
      - localnet
    volumes:
      - data:/data      
networks:
  localnet:
volumes:
  data:
  
